del *.~* /s
del *.zip /s
del *.bmp /s
del *.xml /s
del *.dsk /s
del *.identcache /s
del *.local /s
del *.drc /s
del *.map /s
del *.dof /s
del *.dsk /s
del *.dc?il /s
del *.dcu /s
del *.cfg /s
del *.pdb /s 
del *.cfb /s
del *.rsp /s
del *.tgs /s
del *.tgw /s
del *.ddp /s
del *.bak /s
del *.old /s
del *.tvsconfig /s
del *.xml /s
del *.rar /s
del *.od* /s
del *.Bin /s
del *.lck /s
del *.cbk /s
del *.zip
del *.rar
del *.manifest /s
del *.cache /s
del *.tlog /s
del *.resources /s
del *.exe /s
del*.config /s
del *.tlog /s
del *.manifest /s